---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(waffle)
library(showtext)
library(ggtext)

font_add_google("Inter", "inter")
showtext_auto()

bg_color <- "#D9E3CA"
primary_color <- "#A34100"
secondary_color <- "#5F7C50"
mgn <- 0.4
my_font <- "inter"

tuesdata <- tidytuesdayR::tt_load(2021, week = 15)
```

```{r}
brazil <- tuesdata$brazil_loss %>% 
  pivot_longer(-c(1:3), names_to = "name", values_to = "loss") %>% 
  summarize(name = "Brazil Deforestation", loss = sum(loss),
            is_bra = TRUE)

losses <- brazil %>% 
  rbind(
    tibble(name = c("Italy", "Colorado", "The Great Lakes", "Kyrgyzstan" , "Newfoundland, Canada"),
           loss = c(301318, 269601, 244100, 199900, 170000),
           is_bra = rep(FALSE, 5))
  ) %>%  
  mutate(name = fct_reorder(name, -loss))

my_plot <- losses  %>% 
  ggplot(aes(values = loss / 500, fill = is_bra)) +
  geom_waffle(n_rows = 5, size = 0.6, color = bg_color, show.legend = FALSE) +
  scale_fill_manual(values = c(secondary_color, primary_color)) +
  coord_equal(expand = FALSE) +
  facet_wrap(~name, ncol = 1, strip.position = "left") +
  labs(title = "__<span style = 'color:#A34100;'>Brazil lost more forest</span> in 2001-2013 than size of <span style = 'color:#5F7C50;'>Italy</span>__",
       subtitle = expression(paste("1 square = 630 ", km^2, ", size of Toronto", sep = "")),
       caption = "Visualization: @jiwanheo | Data: ourworldindata.org") + 
  theme_void() +
  theme(
    plot.background = element_rect(fill = bg_color, color = bg_color),
    plot.margin = unit(c(1,1,1,1), "cm"),
    panel.background = element_rect(fill = bg_color, color = bg_color),
    panel.grid = element_blank(),
    
    strip.text.y.left = element_text(angle = 0, size = 20, hjust = 0,
                                     margin = margin(mgn, mgn + 0.5, mgn, mgn, "cm"),
                                     family = my_font, face = "bold"),
    strip.background = element_rect(fill = bg_color, color = bg_color),
    
    axis.ticks = element_blank(),
    axis.text.y = element_blank(),
    axis.text.x = element_blank(),
    
    plot.title = element_markdown(size = 30, family = my_font),
    plot.subtitle = element_text(size = 15, family = my_font, margin = margin(mgn, mgn, mgn + 3, mgn))
  )

my_plot
```

```{r}
my_plot + ggsave(here::here("2021", "2021-week15", "output.png"), device = "png", width = 10, height = 5.1, dpi = 100)
```

