---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytuesdayR)
library(ggimage)
library(here)
library(showtext)

font_add_google("Roboto", "roboto")
font_add_google("Bebas Neue", "bebas")

showtext_auto()

tuesdata <- tidytuesdayR::tt_load(2021, week = 12)
tidytuesdayR::readme(tuesdata)
games <- tuesdata$games

nba2k <- games %>% 
  mutate(date = lubridate::make_date(year, match(month, month.name), 1)) %>% 
  filter(str_detect(gamename, "NBA")) %>% 
  arrange(gamename, date) %>% 
  group_by(gamename) %>% 
  mutate(months_passed = row_number()) %>% 
  ungroup() %>% 
  filter(months_passed <= 18)
```

```{r}
palette <- c("NBA 2K17" = "#fdb927", "NBA 2K18" = "#a1a1a4", "NBA 2K19" = "#051F58", "NBA 2K20" = "#b4975a", "NBA 2K21" = "#e03a3e")

theme_set(theme_minimal())

geom_line_func <- function(game, geom_size) {
  geom_line(data = filter(nba2k, gamename == game), aes(months_passed, avg, color = gamename), size = geom_size)
}

geom_curve_func <- function(game, curve_amt, curve_color) {
  geom_curve(data = filter(arrows, gamename == game), 
             aes(x = x, xend = xend, y = y , yend = yend), 
             arrow = arrow(ends = "last", length = unit(0.1, "inches")),
             color = curve_color, curvature = curve_amt)
}

arrows <- tibble(x = c(2, 16),
                 xend = c(1, 12),
                 y = c(20000, 16000),
                 yend = c(16200, 15000),
                 gamename = c("NBA 2K21", "NBA 2K20"))

images <- tibble(img = c(here("2021", "2021-week12", "2k21.jpg"),
                         here("2021", "2021-week12", "2k20.jpg"),
                         here("2021", "2021-week12", "2k19.jpg"),
                         here("2021", "2021-week12", "2k18.jpg"),
                         here("2021", "2021-week12", "2k17.jpg")),
                 x = c(3, 11, 11, 9, 7),
                 y = c(6033.57, 22884.1, 14469.92, 7932.64, 5126.92),
                 gamename = c("NBA 2K21", "NBA 2K20", "NBA 2K19", "NBA 2K18", "NBA 2K17"))

my_plot <- ggplot() +
  # Had to move around 2k18 & 2k21 to avoid overlapping
  
  geom_image(data = filter(images, gamename == "NBA 2K20"), aes(x, y, image = img), asp = 2.2, size = 0.07) +
  geom_image(data = filter(images, gamename == "NBA 2K19"), aes(x, y, image = img), asp = 2.2, size = 0.07) +
  geom_image(data = filter(images, gamename == "NBA 2K17"), aes(x, y, image = img), asp = 2, size = 0.07) +

  geom_line_func(game = "NBA 2K20", geom_size = 1.8) +
  geom_line_func(game = "NBA 2K19", geom_size = 1.8) +
  geom_line_func(game = "NBA 2K17", geom_size = 1.8) +

  geom_image(data = filter(images, gamename == "NBA 2K18"), aes(x, y, image = img), asp = 2, size = 0.07) +
  geom_line_func(game = "NBA 2K18", geom_size = 1.8) +

  geom_image(data = filter(images, gamename == "NBA 2K21"), aes(x, y, image = img), asp = 2, size = 0.15) +
  geom_line(data = filter(nba2k, gamename == "NBA 2K21"), aes(months_passed, avg, color = gamename), size = 5, linetype = "longdash") +
  
  geom_vline(xintercept = 12, linetype = "dashed", size = 1, color = "red") +
  
  annotate("text", x = 16, y = 15000, label = "12 months after release, \nnext game cycle starts", size = 7, family = "roboto") +
  geom_curve_func("NBA 2K20", 0.2, "grey30") +
  
  annotate("text", x = 2, y = 20100, label = "2K games are typically \nreleased every September", size = 7, family = "roboto", hjust = -0.1) +
  geom_curve_func("NBA 2K21", 0.4, "grey30") +
  
  scale_y_continuous(labels = scales::comma_format()) +
  expand_limits(y = c(0, 25000)) +
  labs(
    title = "NBA 2K21 is Underperforming previous 2 Years so far",
    subtitle = "Avg. # monthly players on Steam during 18 months period after releases of the last 5 NBA 2K games",
    x = "# Months since Release",
    y = "# Avg. Monthly Players",
    color = "Game"
  ) +
  scale_x_continuous(expand = c(0.01,0.02), breaks = seq(0, 24, by = 3)) +
  scale_color_manual(values = palette) +
  theme(
    legend.position = "none",
    plot.background = element_rect(fill = "grey90"),
    plot.margin = unit(c(1,1,1,1), units = "cm"),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(color = "#ffffff"),
    
    plot.title = element_text(size = 60, family = "bebas", vjust = 2),
    plot.subtitle = element_text(size = 20, family = "roboto", vjust = 2),
    
    axis.title.x = element_text(size = 20, family = "roboto", vjust = -2),
    axis.title.y = element_text(size = 20, family = "roboto", vjust = 5),
    axis.text = element_text(size = 20, family = "roboto")
  ) +
  
  annotate("text", x = 16, y = 30000, label = "Visualization: @jiwanheo | Data: TidyTuesday", size = 4, family = "roboto")

my_plot
```

